version: '2'
services:
    db:
        container_name: yii2mod-db-container
        build:
            context: ./data/docker/db
            args:
                HOST_UID: ${HOST_UID}
        restart: always
        volumes:
            - ./runtime/db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: yii2mod_base
            MYSQL_USER: yii2mod
            MYSQL_PASSWORD: secret

    web:
        container_name: yii2mod-web-container
        build:
            context: ./data/docker/web
            args:
                HOST_UID: ${HOST_UID}
        restart: always
        volumes:
            - .:/var/www/html
        links:
            - db
        depends_on:
            - db
