<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => 'Acción',
    'Are you sure you want to clear this table?' => '¿Estás seguro de que quieres borrar esta tabla?',
    'Are you sure you want to switch to this user for the rest of this Session?' => '¿Estás seguro de que quieres cambiar a este usuario por el resto de esta sesión?',
    'Become this user' => 'Conviértete en este usuario',
    'Cancel' => 'Cancelar',
    'Change Password' => 'Cambiar contraseña',
    'Confirm New Password' => 'Confirmar nueva contraseña',
    'Create' => 'Crear',
    'Create User' => 'Crear usuario',
    'My Account' => 'Mi cuenta',
    'New Password' => 'Nueva contraseña',
    'Password has been updated.' => 'La contraseña se ha actualizado.',
    'Personal Information' => 'Información personal',
    'Save' => 'Guardar',
    'Select Status' => 'Seleccionar estado',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Gracias por contactarnos. Nosotros responderemos a la mayor brevedad posible.',
    'There was an error sending email.' => 'Hubo un error al enviar un correo electrónico',
    'Update' => 'Actualización',
    'Update User: {0}' => 'Actualizar usuario: {0}',
    'User has been created.' => 'El usuario ha sido creado.',
    'User has been deleted.' => 'El usuario ha sido eliminado.',
    'User has been saved.' => 'El usuario se ha guardado.',
    'Users' => 'Usuarios',
];
