<?php

return [
    'ingredients0' => [
        'uuid' => 'd25270f4-87e4-3f13-bdef-672f075b79d7',
        'group_food_id' => 2,
        'type_ingredient_id' => 2,
        'name' => 'Prof. Coralie Gulgowski V',
        'description' => 'Eligendi unde sunt maxime incidunt ut enim deserunt itaque.',
        'protein_per_gram' => 1.5,
        'color' => '#002211',
        'type' => '*',
    ],
    'ingredients1' => [
        'uuid' => '882a6599-f966-311e-9316-9c1fa0125a01',
        'group_food_id' => 5,
        'type_ingredient_id' => 3,
        'name' => 'Hyman Padberg',
        'description' => 'Qui esse a tempore voluptas quisquam impedit.',
        'protein_per_gram' => 0.15,
        'color' => '#0011dd',
        'type' => '*',
    ],
    'ingredients2' => [
        'uuid' => 'e10817d6-6edb-34fe-b0b0-79244e232699',
        'group_food_id' => 5,
        'type_ingredient_id' => 3,
        'name' => 'Shawn Satterfield V',
        'description' => 'Cum veritatis natus rem ratione neque sint perferendis cupiditate.',
        'protein_per_gram' => 1.1,
        'color' => '#007777',
        'type' => '*',
    ],
    'ingredients3' => [
        'uuid' => 'ffc66579-9ec6-3cea-b1f1-1e65a0563fe2',
        'group_food_id' => 4,
        'type_ingredient_id' => 2,
        'name' => 'Yvonne Strosin',
        'description' => 'Maxime sit veritatis similique ipsum rem.',
        'protein_per_gram' => 1.28,
        'color' => '#009944',
        'type' => '*',
    ],
    'ingredients4' => [
        'uuid' => 'a6116aaa-39ed-3737-8a0f-ed560eb1eb53',
        'group_food_id' => 1,
        'type_ingredient_id' => 4,
        'name' => 'Christina Herman III',
        'description' => 'Sed omnis in laudantium at sequi.',
        'protein_per_gram' => 0.22,
        'color' => '#0099ee',
        'type' => '*',
    ],
    'ingredients5' => [
        'uuid' => '55a5cbfc-e7a1-376e-bb4a-c859c518bbc6',
        'group_food_id' => 6,
        'type_ingredient_id' => 4,
        'name' => 'Dr. Nia Pfeffer',
        'description' => 'Qui consequuntur ad a.',
        'protein_per_gram' => 1.68,
        'color' => '#0044ff',
        'type' => '*',
    ],
    'ingredients6' => [
        'uuid' => 'd4397df0-4e97-3c02-b3bb-dd2277207980',
        'group_food_id' => 2,
        'type_ingredient_id' => 4,
        'name' => 'Cassandre Kiehn',
        'description' => 'Corrupti assumenda commodi iusto qui vitae.',
        'protein_per_gram' => 0.15,
        'color' => '#0066ee',
        'type' => '*',
    ],
    'ingredients7' => [
        'uuid' => '618da6bf-6454-39e2-aa96-2e0781a7f049',
        'group_food_id' => 2,
        'type_ingredient_id' => 4,
        'name' => 'Precious Nicolas',
        'description' => 'Quia non est placeat quia dolore assumenda.',
        'protein_per_gram' => 0.92,
        'color' => '#006622',
        'type' => '*',
    ],
    'ingredients8' => [
        'uuid' => 'f746cc21-90d8-3520-b388-bc39f2bee5a8',
        'group_food_id' => 5,
        'type_ingredient_id' => 3,
        'name' => 'Kyle Kshlerin',
        'description' => 'Cum cupiditate ea id molestiae aut perferendis ducimus provident.',
        'protein_per_gram' => 1.46,
        'color' => '#000099',
        'type' => '*',
    ],
    'ingredients9' => [
        'uuid' => 'bff9d3c0-b513-3b30-b0ad-f4b147229aa8',
        'group_food_id' => 2,
        'type_ingredient_id' => 4,
        'name' => 'Prof. Mariah Pfannerstill',
        'description' => 'Suscipit dignissimos dolores sed quam autem perferendis.',
        'protein_per_gram' => 1.48,
        'color' => '#00dd44',
        'type' => '*',
    ],
    'ingredients10' => [
        'uuid' => 'd1b821e0-0431-33d5-b73d-c6de4a53d689',
        'group_food_id' => 6,
        'type_ingredient_id' => 2,
        'name' => 'Prof. Lexus Goyette Jr.',
        'description' => 'Quos explicabo unde sunt quibusdam quaerat eum consectetur.',
        'protein_per_gram' => 1.44,
        'color' => '#0088dd',
        'type' => '*',
    ],
    'ingredients11' => [
        'uuid' => 'e96051cc-4059-3edf-bb56-0cbc258d1edc',
        'group_food_id' => 5,
        'type_ingredient_id' => 1,
        'name' => 'Greta Cruickshank',
        'description' => 'Ab dolore sit sit doloribus aut velit sunt.',
        'protein_per_gram' => 1.0,
        'color' => '#008800',
        'type' => '*',
    ],
    'ingredients12' => [
        'uuid' => '5bec7c1a-ffbe-3a5a-92e6-5f3831434b96',
        'group_food_id' => 1,
        'type_ingredient_id' => 4,
        'name' => 'Amely Bogan',
        'description' => 'Aut natus est soluta voluptatem.',
        'protein_per_gram' => 1.03,
        'color' => '#004466',
        'type' => '*',
    ],
    'ingredients13' => [
        'uuid' => '4e903102-8a01-357f-8644-44267df5f237',
        'group_food_id' => 4,
        'type_ingredient_id' => 2,
        'name' => 'Cristian Howell DVM',
        'description' => 'Beatae suscipit ea rerum dolor et fuga voluptatibus.',
        'protein_per_gram' => 1.71,
        'color' => '#00cc88',
        'type' => '*',
    ],
    'ingredients14' => [
        'uuid' => 'a724f7d7-2825-3bf4-a68d-1e71cd8eda10',
        'group_food_id' => 1,
        'type_ingredient_id' => 3,
        'name' => 'Miss Oleta Daugherty Sr.',
        'description' => 'Consequatur nihil aut quisquam non quia velit.',
        'protein_per_gram' => 1.53,
        'color' => '#0022ff',
        'type' => '*',
    ],
    'ingredients15' => [
        'uuid' => 'e29f0109-f1f9-3d9e-9f13-c2cfd161526e',
        'group_food_id' => 6,
        'type_ingredient_id' => 2,
        'name' => 'Sierra Trantow',
        'description' => 'Enim eum id dicta ab.',
        'protein_per_gram' => 0.32,
        'color' => '#0055dd',
        'type' => '*',
    ],
    'ingredients16' => [
        'uuid' => '85117893-fa56-306b-aa8a-9211141ad754',
        'group_food_id' => 4,
        'type_ingredient_id' => 2,
        'name' => 'Destiney Prosacco',
        'description' => 'Consequatur rerum dolorum omnis ut.',
        'protein_per_gram' => 1.72,
        'color' => '#006600',
        'type' => '*',
    ],
    'ingredients17' => [
        'uuid' => '72b7a797-a09c-3b84-8a4a-7afe93895ba7',
        'group_food_id' => 1,
        'type_ingredient_id' => 3,
        'name' => 'Mrs. Elvie Swift DDS',
        'description' => 'Quae exercitationem ipsa necessitatibus quaerat velit.',
        'protein_per_gram' => 1.71,
        'color' => '#0077ee',
        'type' => '*',
    ],
    'ingredients18' => [
        'uuid' => 'c9f0c22b-b1bc-3f8f-9b54-4e52f9aefc92',
        'group_food_id' => 4,
        'type_ingredient_id' => 2,
        'name' => 'Emery Trantow',
        'description' => 'Sed labore qui eum perspiciatis aut et.',
        'protein_per_gram' => 1.18,
        'color' => '#00ddee',
        'type' => '*',
    ],
    'ingredients19' => [
        'uuid' => '4f313c01-f6b5-3f2e-85ee-992db0b38251',
        'group_food_id' => 4,
        'type_ingredient_id' => 1,
        'name' => 'Yazmin Gleason',
        'description' => 'Voluptatibus maiores sequi vel vel explicabo quia tempora.',
        'protein_per_gram' => 1.38,
        'color' => '#0077cc',
        'type' => '*',
    ],
];
