<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => '',
    'Are you sure you want to clear this table?' => '',
    'Are you sure you want to switch to this user for the rest of this Session?' => '',
    'Become this user' => '',
    'Cancel' => '',
    'Change Password' => '',
    'Confirm New Password' => '',
    'Create' => '',
    'Create User' => '',
    'My Account' => '',
    'New Password' => '',
    'Password has been updated.' => '',
    'Personal Information' => '',
    'Save' => '',
    'Select Status' => '',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '',
    'There was an error sending email.' => '',
    'Update' => '',
    'Update User: {0}' => '',
    'User has been created.' => '',
    'User has been deleted.' => '',
    'User has been saved.' => '',
    'Users' => '',
];
